DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS admin (
  id       INT PRIMARY KEY AUTO_INCREMENT,
  password VARCHAR(20) NOT NULL,
  username VARCHAR(20) NOT NULL,
  token    VARCHAR(50) NOT NULL
);